/**
 * Evidence store — every step the agent takes on behalf of the user is
 * recorded as an immutable text artifact uploaded to Base44 storage.
 *
 * These artifacts back the case's audit trail: if a claim gets escalated
 * to a DOT complaint or legal action, the file_url references are the
 * chain of custody the agent presents.
 */
import { base44 } from "@/api/base44Client";

const shortHash = async (text) => {
  if (typeof crypto?.subtle?.digest === "function") {
    const buf = new TextEncoder().encode(text);
    const digest = await crypto.subtle.digest("SHA-256", buf);
    return Array.from(new Uint8Array(digest))
      .slice(0, 8)
      .map((b) => b.toString(16).padStart(2, "0"))
      .join("");
  }
  return String(text.length).padStart(8, "0");
};

const formatArtifact = ({ caseItem, log, hash }) => {
  const ts = new Date().toISOString();
  const meta = log.metadata ? JSON.stringify(log.metadata, null, 2) : "{}";
  return [
    "ENVOY — PASSENGER-ADVOCATE EVIDENCE ARTIFACT",
    "=========================================",
    `Recorded at:      ${ts}`,
    `Case number:      ${caseItem?.case_number || "—"}`,
    `Case id:          ${caseItem?.id || "—"}`,
    `Flight:           ${caseItem?.flight_number || "—"} (${caseItem?.origin || "?"} → ${caseItem?.destination || "?"})`,
    `Airline:          ${caseItem?.airline_name || "—"}`,
    `Regulation cited: ${caseItem?.applicable_regulation || "—"}`,
    "",
    "--- COMMUNICATION EVENT ---",
    `Direction:        ${log.direction}`,
    `Channel:          ${log.channel}`,
    `Sender:           ${log.sender}`,
    `Recipient:        ${log.direction === "outbound" ? caseItem?.airline_name || "Airline" : "Envoy"}`,
    "",
    "--- MESSAGE BODY ---",
    log.content || "",
    "--- END MESSAGE ---",
    "",
    `Structured metadata:`,
    meta,
    "",
    `Integrity hash:   sha256-${hash}`,
    "Custody notice:   Stored immutably for use in DOT (14 CFR Part 259)",
    "                  complaints and downstream legal escalation.",
    "",
    "Generated by Envoy — Passenger Advocate",
  ].join("\n");
};

const safeName = (s) => (s || "log").replace(/[^A-Za-z0-9._-]+/g, "_").slice(0, 40);

/**
 * Build + upload an evidence artifact for a communication log entry.
 * Returns `{ file_url, hash, size }` or `null` if upload fails.
 * Never throws — the caller should still create the log entry either way.
 */
export async function uploadEvidence({ caseItem, log }) {
  try {
    const hash = await shortHash(log.content || "");
    const text = formatArtifact({ caseItem, log, hash });
    const filename = `evidence_${safeName(caseItem?.case_number)}_${Date.now()}.txt`;
    const file = new File([text], filename, { type: "text/plain" });
    const { file_url } = await base44.integrations.Core.UploadFile({ file });
    return { file_url, hash, size: file.size };
  } catch (err) {
    console.warn("[evidenceStore] upload failed:", err);
    return null;
  }
}

/**
 * Convenience: create a CommunicationLog entry AND upload its evidence
 * artifact in one call. The artifact URL and integrity hash are stored
 * on the log's `metadata` field so the audit trail is queryable.
 */
export async function logWithEvidence({ caseItem, log }) {
  const evidence = await uploadEvidence({ caseItem, log });
  const metadata = {
    ...(log.metadata || {}),
    ...(evidence
      ? {
          artifact_url: evidence.file_url,
          artifact_hash: evidence.hash,
          artifact_size: evidence.size,
        }
      : {}),
  };
  return base44.entities.CommunicationLog.create({ ...log, metadata });
}
